#!/usr/bin/env bash
#
# Provision the demo into your own subscription and load the data.
#
#   ./scripts/setup.sh                                  use your current az login
#   ./scripts/setup.sh --location westeurope            pick a region
#   ./scripts/setup.sh --prefix contoso --open-firewall
#   ./scripts/setup.sh --infra-only                     stop after terraform
#   ./scripts/setup.sh --no-run                         set everything up, do not start the app
#
# Everything is Entra ID. No key, password or connection string is created,
# stored or printed by this script.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$HERE/infra/terraform"
TFVARS="$TF_DIR/terraform.tfvars"
ENV_FILE="$HERE/.env"

LOCATION="swedencentral"
PREFIX="aidb"
SUBSCRIPTION=""
OPEN_FIREWALL="false"
INFRA_ONLY="false"
RUN_APP="true"
AUTO_APPROVE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --location)       LOCATION="$2"; shift 2 ;;
    --prefix)         PREFIX="$2"; shift 2 ;;
    --subscription)   SUBSCRIPTION="$2"; shift 2 ;;
    --open-firewall)  OPEN_FIREWALL="true"; shift ;;
    --infra-only)     INFRA_ONLY="true"; shift ;;
    --no-run)         RUN_APP="false"; shift ;;
    --yes)            AUTO_APPROVE="-auto-approve"; shift ;;
    -h|--help)        sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 1 ;;
  esac
done

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }

for tool in az terraform python3; do
  command -v "$tool" >/dev/null || { echo "missing required tool: $tool" >&2; exit 1; }
done

# --------------------------------------------------------------------- identity

say "Reading your Azure context"
az account show >/dev/null 2>&1 || { echo "run 'az login' first" >&2; exit 1; }
[[ -n "$SUBSCRIPTION" ]] && az account set --subscription "$SUBSCRIPTION"

SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
TENANT_ID="$(az account show --query tenantId -o tsv)"
ACCOUNT_NAME="$(az account show --query name -o tsv)"

# A user signs in with a UPN; a service principal has none and uses its app id.
PRINCIPAL_ID="$(az ad signed-in-user show --query id -o tsv 2>/dev/null || true)"
if [[ -n "$PRINCIPAL_ID" ]]; then
  PRINCIPAL_NAME="$(az ad signed-in-user show --query userPrincipalName -o tsv)"
  PRINCIPAL_TYPE="User"
else
  PRINCIPAL_ID="$(az account show --query user.name -o tsv)"
  PRINCIPAL_NAME="$PRINCIPAL_ID"
  PRINCIPAL_TYPE="ServicePrincipal"
fi

echo "  subscription  $ACCOUNT_NAME"
echo "  signed in as  $PRINCIPAL_NAME ($PRINCIPAL_TYPE)"
echo "  region        $LOCATION"
echo "  name prefix   $PREFIX"

if [[ "$OPEN_FIREWALL" == "true" ]]; then
  IP_RULES="[]"
  echo "  firewall      open to every address"
else
  MY_IP="$(curl -fsS https://api.ipify.org)"
  IP_RULES="[\"$MY_IP/32\"]"
  echo "  firewall      $MY_IP only"
fi

# ------------------------------------------------------------------- terraform

say "Writing $TFVARS"
cat > "$TFVARS" <<EOF
# Generated by scripts/setup.sh on $(date -u '+%Y-%m-%d %H:%M UTC').
# Gitignored. No secrets, but these ids are yours.

subscription_id = "$SUBSCRIPTION_ID"
tenant_id       = "$TENANT_ID"

location    = "$LOCATION"
name_prefix = "$PREFIX"

postgres_entra_admin_object_id = "$PRINCIPAL_ID"
postgres_entra_admin_name      = "$PRINCIPAL_NAME"
postgres_entra_admin_type      = "$PRINCIPAL_TYPE"

admin_object_ids     = ["$PRINCIPAL_ID"]
admin_principal_type = "$PRINCIPAL_TYPE"

allowed_ip_rules   = $IP_RULES
allow_all_networks = $OPEN_FIREWALL
EOF

say "terraform init"
terraform -chdir="$TF_DIR" init -input=false

say "terraform apply"
terraform -chdir="$TF_DIR" apply -input=false $AUTO_APPROVE

say "Writing $ENV_FILE"
terraform -chdir="$TF_DIR" output -json dotenv | python3 -c '
import json, sys
values = json.load(sys.stdin)
print("# Generated by scripts/setup.sh. No secrets: everything authenticates with Entra ID.")
for key, value in values.items():
    print(f"{key}={value}")
' > "$ENV_FILE"

if [[ "$INFRA_ONLY" == "true" ]]; then
  say "Infrastructure ready. Skipping the data load."
  exit 0
fi

# ------------------------------------------------------------------------ data

if [[ ! -d "$HERE/.venv" ]]; then
  say "Creating the virtual environment"
  python3 -m venv "$HERE/.venv"
fi
# shellcheck disable=SC1091
source "$HERE/.venv/bin/activate"
pip install --quiet --upgrade pip
pip install --quiet -r "$HERE/requirements.txt"

cd "$HERE"

# Role assignments are eventually consistent, and the first data-plane call
# after an apply often lands before they have propagated.
say "Waiting for the role assignments to propagate"
sleep 60

say "Loading Cosmos DB"
python -m tools.load_cosmos --recreate

say "Loading PostgreSQL"
python -m tools.load_postgres --recreate

say "Building the graph"
python -m tools.load_graph --recreate

say "Preflight"
python -m tools.preflight || true

RG="$(terraform -chdir="$TF_DIR" output -raw resource_group_name)"
PG_NAME="$(terraform -chdir="$TF_DIR" output -raw postgres_host | cut -d. -f1)"

cat <<EOF

------------------------------------------------------------------------
Everything is provisioned and loaded.

  python -m tools.smoke       exercise every panel from the command line
  python -m tools.preflight   check the environment is still demo-ready

The PostgreSQL server is the expensive part. Stop it when you are done:

  az postgres flexible-server stop -g $RG -n $PG_NAME

Remove all of it:

  terraform -chdir=infra/terraform destroy
------------------------------------------------------------------------
EOF

if [[ "$RUN_APP" != "true" ]]; then
  echo
  echo "Start the demo yourself with: python -m app.app"
  exit 0
fi

say "Starting the demo on http://127.0.0.1:5000  (Ctrl-C to stop)"
# Foreground on purpose: Ctrl-C should stop the demo, not orphan it.
exec python -m app.app
